# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

# Setup
gems: 				 [jekyll-paginate]
title:               Lanyon
tagline:             'A Jekyll theme'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Custom vars
version:             1.0.0
excerpt_separator: <!--more-->

collections:
  algoritma:
    output: true